fix(miner): added retry to batch templates to prevent crashing

diff --git a/api/templates/cpu.tmpl b/api/templates/cpu.tmpl
--- a/api/templates/cpu.tmpl
+++ b/api/templates/cpu.tmpl
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/env bash
 #SBATCH --ntasks=1
 #SBATCH --array=1-{{ .Node }}
 #SBATCH --gpus-per-task=0
@@ -6,6 +6,20 @@
 #SBATCH --mem-per-cpu=8G
 
 cont='registry-1.deepsquare.run#library/xmrig'
+retry_failed=true # Indicates if last attempt failed
+retry_delay=30  # Delay in seconds
 
-srun --ntasks=1 --cpus-per-task={{ .Core }} --mem-per-cpu=8G --container-image="$cont" \
-  sh -c '/app/xmrig --algo={{ .Algo }} --url={{ .Pool }} --user={{ .Wallet }}.$(hostname)-$SLURM_ARRAY_TASK_ID --tls --nicehash'
+while [ "$retry_failed" = true ]; do
+  srun --ntasks=1 --cpus-per-task={{ .Core }} --mem-per-cpu=8G --container-image="$cont" \
+    bash -c '/app/xmrig --algo={{ .Algo }} --url={{ .Pool }} --user={{ .Wallet }}.$(hostname)-$SLURM_ARRAY_TASK_ID --tls --nicehash'
+
+  exit_code=$?
+  if [ $exit_code -eq 0 ]; then
+    echo "Script completed successfully."
+    retry_failed=false
+    break
+  else
+    echo "Script exited with code $exit_code. Retrying..."
+    sleep $retry_delay
+  fi
+done
diff --git a/api/templates/job.tmpl b/api/templates/job.tmpl
--- a/api/templates/job.tmpl
+++ b/api/templates/job.tmpl
@@ -6,6 +6,21 @@
 #SBATCH --mem-per-cpu=16G
 
 cont='registry-1.deepsquare.run#library/gminer'
+retry_failed=true # Indicates if last attempt failed
+retry_delay=30  # Delay in seconds
 
-srun --cpu-bind=none --ntasks=1 --gpus-per-task=1 --cpus-per-task=1 --mem-per-cpu=16G --container-image="$cont" \
-  bash -c 'miner --algo {{ .Algo }} --server {{ .Pool }} --proto stratum --ssl 1 --user {{ .Wallet }}.$(hostname)-$SLURM_ARRAY_TASK_ID --pass x'
+while [ "$retry_failed" = true ]; do
+  srun --cpu-bind=none --ntasks=1 --gpus-per-task=1 --cpus-per-task=1 --mem-per-cpu=16G --container-image="$cont" \
+    bash -c 'miner --algo {{ .Algo }} --server {{ .Pool }} --proto stratum --ssl 1 --user {{ .Wallet }}.$(hostname)-$SLURM_ARRAY_TASK_ID --pass x'
+
+  exit_code=$?
+  if [ $exit_code -eq 0 ]; then
+    echo "Script completed successfully."
+    retry_failed=false
+    break
+  else
+    echo "Script exited with code $exit_code. Retrying..."
+    sleep $retry_delay
+  fi
+done
+
